### ISSUE TITLE
Info about upcoming removal of packages in the General registry

### ISSUE THREAD

**Issue by KristofferC** [PerezHz/HORIZONS.jl#10]
As described in https://discourse.julialang.org/t/ann-plans-for-removing-packages-that-do-not-yet-support-1-0-from-the-general-registry/ we are planning on removing packages that do not support 1.0 from the General registry. This package has been detected to not support 1.0 and is thus slated to be removed. The removal of packages from the registry will happen approximately a month after this issue is open.

To transition to the new Pkg system using `Project.toml`, see https://github.com/JuliaRegistries/Registrator.jl#transitioning-from-require-to-projecttoml.
To then tag a new version of the package, see https://github.com/JuliaRegistries/Registrator.jl#via-the-github-app.

If you believe this package has erroneously been detected as not supporting 1.0 or have any other questions, don't hesitate to discuss it here or in the thread linked at the top of this post.

**Comment by PerezHz** [comment]
@KristofferC now that HORIZONS.jl has a version compatible with julia 1.0, would it be fine to close this issue? (I mistakenly closed it before the new version was merged in the General registry)

**Comment by KristofferC** [comment]
Yep, thanks for updating!

**Comment by KristofferC** [comment]
Actually, this package depends on Expect which does not support 1.0 so it would still be removed. Trying to install it on 1.0 gives

```
(v1.2) pkg> add HORIZONS
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Expect [6a31a4e8]:
 Expect [6a31a4e8] log:
 ├─possible versions are: [0.0.1, 0.1.0-0.1.2, 0.2.0-0.2.3] or uninstalled
 ├─restricted by compatibility requirements with HORIZONS [5a3ac768] to versions: [0.0.1, 0.1.0-0.1.2, 0.2.0-0.2.3]
 │ └─HORIZONS [5a3ac768] log:
 │   ├─possible versions are: [0.0.1, 0.1.0] or uninstalled
 │   ├─restricted to versions * by an explicit requirement, leaving only versions [0.0.1, 0.1.0]
 │   └─restricted by julia compatibility requirements to versions: 0.1.0 or uninstalled, leaving only versions: 0.1.0
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left
```

**Comment by PerezHz** [comment]
Thanks for checking this; actually I had to fork Expect.jl and checkin a Manifest in HORIZONS.jl pointing to the [fork](https://github.com/PerezHz/Expect.jl.git) I created. I have been trying to contact the repo maintainer @wavexx but so far have been unsuccessful to have a registered version of Expect.jl compatible with julia1.0 (by the way, Expect.jl was migrated to [GitLab](https://gitlab.com/wavexx/Expect.jl)). So I meant this as a temporary solution so that HORIZONS.jl could be brought to julia1.0, but if there's a better solution I'm happy to change things to comply with best practices 😄 . By the way, in the code you posted, it seems that you actually tested on julia1.2?

**Comment by KristofferC** [comment]
Yeah, but the result is the same on 1.0. The problem here is that unless Expect.jl updates it will be removed and we can't have a package depend on a removed package like Horizon the would do. 

One possibility is to just copy paste the Expect.jl into this package (it is only one file) and tag a new release not depending on Expect. Then this package is fine and will be kept.

**Comment by PerezHz** [comment]
Thanks @KristofferC! Just opened JuliaRegistries/General#3405 with your suggestions

**Comment by PerezHz** [comment]
Could you please confirm if this issue is fixed in HORIZONS.jl v0.1.1?
